baseurl:
title: Ujjwal Upadhyay
author: Ujjwal Upadhyay
simple_search: http://google.com/search
description: Personal webpage
name: Ujjwal Upadhyay
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
timezone: America/Chicago
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md', 'vendor']
post:
  template: _post.txt
  extension: md
#page:
#  template: _page.txt
#  extension: md
editor: vim
plugins:
    - jekyll-seo-tag
    - jekyll-youtube
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/
  destination: ~/Git/clayh53.github.com/
google_analytics: UA-112402500-1
